import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import '../models/analysis.dart';
import '../models/analysis_summary.dart';
import 'analyze_request.dart';

part 'ilgo_api.g.dart';

/// Retrofit client. Implementation (`_IlgoApi`) is generated by build_runner.
@RestApi()
abstract class IlgoApi {
  factory IlgoApi(Dio dio, {String? baseUrl}) = _IlgoApi;

  @POST('/analyses')
  Future<Analysis> analyze(@Body() AnalyzeRequest body);

  @GET('/analyses')
  Future<AnalysisListResponse> list(@Query('cursor') String? cursor);

  @GET('/analyses/{id}')
  Future<Analysis> getById(@Path('id') String id);

  @DELETE('/analyses/{id}')
  Future<void> delete(@Path('id') String id);
}
