import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import '../models/analysis.dart';
import '../models/analysis_summary.dart';
import '../models/api_responses.dart';
import '../models/auth.dart';
import '../models/help_contact.dart';
import '../models/profile.dart';
import 'analyze_request.dart';

part 'ilgo_api.g.dart';

/// Retrofit client for the Ilgo backend. Implementation (`_IlgoApi`) is
/// generated by build_runner. Request bodies use plain maps to avoid extra
/// codegen; responses are typed models.
@RestApi()
abstract class IlgoApi {
  factory IlgoApi(Dio dio, {String? baseUrl}) = _IlgoApi;

  // ── Auth ────────────────────────────────────────────────────────────
  @POST('/auth/register')
  Future<AuthResponse> register(@Body() Map<String, dynamic> body);

  @POST('/auth/login')
  Future<AuthResponse> login(@Body() Map<String, dynamic> body);

  @POST('/auth/refresh')
  Future<AuthResponse> refresh(@Body() Map<String, dynamic> body);

  @POST('/auth/logout')
  Future<void> logout(@Body() Map<String, dynamic> body);

  @GET('/auth/me')
  Future<MeResponse> me();

  // ── Profile ─────────────────────────────────────────────────────────
  @GET('/profile')
  Future<ProfileResponse> getProfile();

  @PUT('/profile')
  Future<ProfileResponse> putProfile(@Body() Map<String, dynamic> body);

  // ── Analyses ────────────────────────────────────────────────────────
  @POST('/analyses')
  Future<Analysis> analyze(@Body() AnalyzeRequest body);

  @GET('/analyses')
  Future<AnalysisListResponse> list(@Query('cursor') String? cursor);

  @GET('/analyses/{id}')
  Future<Analysis> getById(@Path('id') String id);

  @DELETE('/analyses/{id}')
  Future<void> delete(@Path('id') String id);

  @PATCH('/analyses/{id}/actions/{actionId}')
  Future<ActionToggleResponse> toggleAction(
    @Path('id') String id,
    @Path('actionId') String actionId,
    @Body() Map<String, dynamic> body,
  );

  @POST('/analyses/{id}/replies:regenerate')
  Future<RepliesRegenerateResponse> regenerateReplies(
    @Path('id') String id,
    @Body() Map<String, dynamic> body,
  );

  @POST('/analyses/{id}/feedback')
  Future<FeedbackResponse> feedback(
    @Path('id') String id,
    @Body() Map<String, dynamic> body,
  );

  // ── Help ────────────────────────────────────────────────────────────
  @GET('/help-contacts')
  Future<HelpContactsResponse> helpContacts(
    @Query('lang') String? lang,
    @Query('doc_type') String? docType,
  );
}
